import type { Metadata } from "next";
import { Geist, Geist_Mono, Tiro_Bangla } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";

const tiro_Bangla = Tiro_Bangla({
 weight: "400" 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tiro_Bangla.className} antialiased`}
      >
        {/* <Header>
        </Header> */}
        {children}
      </body>
    </html>
  );
}
